import type { AnalysisReport } from './types';

function list(items: string[], fallback = '_None identified._'): string {
  if (items.length === 0) return fallback;
  return items.map((item) => `- ${item}`).join('\n');
}

/**
 * Renders an AnalysisReport as a standalone Markdown document, covering the
 * same sections ReportDisplay shows in the UI, in the same order.
 */
export function reportToMarkdown(report: AnalysisReport): string {
  const sections: string[] = [];

  sections.push(`# PilotCraft Adoption Strategy Report`);
  sections.push(
    `_Generated by PilotCraft. The readiness score is a planning heuristic, not an objective measurement - see the Evidence Check section before acting on this report._`
  );

  sections.push(`## Scenario Assessment\n\n${report.problemStatement}`);

  sections.push(
    `## AI Suitability\n\n**Rating:** ${report.aiSuitability.rating}\n\n${report.aiSuitability.rationale}`
  );

  sections.push(
    `## Readiness Score\n\n**${report.readinessScore.score}%** - ${report.readinessScore.explanation}\n\n**Factors reducing the score:**\n${list(report.readinessScore.factorsReducingScore)}`
  );

  sections.push(`## Clarifying Questions\n\n${report.clarifyingQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n')}`);

  sections.push(
    [
      `## Evidence Check`,
      ``,
      `**User-Provided Facts:**`,
      list(report.evidenceCheck.userProvidedFacts, '_None extracted._'),
      ``,
      `**Assumptions:**`,
      list(report.evidenceCheck.assumptions, '_No major assumptions identified._'),
      ``,
      `**Missing Evidence:**`,
      list(report.evidenceCheck.missingEvidence, '_Information complete._'),
    ].join('\n')
  );

  sections.push(
    [
      `## Future Workflow`,
      ``,
      `| Step | Human Role | AI Role |`,
      `|---|---|---|`,
      ...report.futureWorkflow.map((w) => `| ${w.step} | ${w.humanRole} | ${w.aiRole} |`),
    ].join('\n')
  );

  sections.push(
    [
      `## Human / AI Responsibility Split`,
      ``,
      `**Stays with humans:**`,
      list(report.responsibilitySplit.human),
      ``,
      `**Handled by AI:**`,
      list(report.responsibilitySplit.ai),
    ].join('\n')
  );

  sections.push(
    [
      `## Risk Assessment`,
      report.risks
        .map((r) => `### ${r.risk} (${r.severity})\n\n- **Safeguard:** ${r.safeguard}\n- **Human review:** ${r.humanReview}`)
        .join('\n\n'),
    ].join('\n\n')
  );

  sections.push(
    [
      `## Stakeholder Impact`,
      ``,
      `| Role | Impact | Involvement |`,
      `|---|---|---|`,
      ...report.stakeholders.map((s) => `| ${s.role} | ${s.impact} | ${s.involvement} |`),
    ].join('\n')
  );

  sections.push(
    [
      `## Adoption Barriers`,
      ``,
      ...report.adoptionBarriers.map((b) => `- **${b.barrier}** - Mitigation: ${b.mitigation}`),
    ].join('\n')
  );

  sections.push(
    [
      `## Training & Communication`,
      ``,
      `**Training actions:**`,
      list(report.trainingAndCommunication.trainingActions),
      ``,
      `**Communication actions:**`,
      list(report.trainingAndCommunication.communicationActions),
    ].join('\n')
  );

  sections.push(
    [
      `## Pilot Implementation Plan`,
      report.pilotPlan
        .map(
          (p) =>
            `### ${p.period} (Owner: ${p.suggestedOwner})\n\n**Actions:**\n${list(p.actions)}\n\n**Evidence to collect:** ${p.evidenceToCollect.join(', ')}`
        )
        .join('\n\n'),
    ].join('\n\n')
  );

  sections.push(
    [
      `## Success Metrics`,
      ``,
      `| Metric | Baseline | Target | Collection Method |`,
      `|---|---|---|---|`,
      ...report.successMetrics.map((m) => `| ${m.metric} | ${m.baseline} | ${m.proposedTarget} | ${m.collectionMethod} |`),
    ].join('\n')
  );

  sections.push(
    [
      `## Go / No-Go Criteria`,
      ``,
      `**Stop:**`,
      list(report.decisionCriteria.stop),
      ``,
      `**Revise:**`,
      list(report.decisionCriteria.revise),
      ``,
      `**Scale:**`,
      list(report.decisionCriteria.scale),
    ].join('\n')
  );

  return sections.join('\n\n') + '\n';
}
